# Generated by Django 3.1.2 on 2020-10-21 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('types', models.SmallIntegerField(choices=[(11, '成人票'), (12, '儿童票')], default=11, help_text='默认成人票', verbose_name='类型')),
                ('price', models.FloatField(default=0, verbose_name='原价')),
                ('discount', models.FloatField(blank=True, default=10, null=True, verbose_name='折扣')),
                ('total_stock', models.PositiveIntegerField(default=0, verbose_name='总库存')),
                ('remain_stock', models.PositiveIntegerField(default=0, verbose_name='剩余库存')),
                ('expire_date', models.DateTimeField(default=1, verbose_name='有效期')),
                ('return_policy', models.CharField(default='条件退', max_length=1024, verbose_name='退改政策')),
                ('has_invoice', models.BooleanField(default=True, verbose_name='是否提供发票')),
                ('enty_way', models.SmallIntegerField(choices=[(1, '短信换票入园'), (0, '凭借验证码入园')], default=0, help_text='默认凭借验证码入园', verbose_name='入园方式')),
                ('tips', models.CharField(blank=True, max_length=1024, null=True, verbose_name='预定须知')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='其他说明')),
                ('status', models.SmallIntegerField(choices=[(1, '开放购买'), (0, '暂未开放')], default=1, help_text='默认开放', verbose_name='状态')),
                ('sight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='sight.sight', verbose_name='景点门票')),
            ],
            options={
                'db_table': 'sight_tickets',
            },
        ),
        migrations.CreateModel(
            name='SightInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('entry_explain', models.TextField(blank=True, max_length=1024, null=True, verbose_name='入园参考')),
                ('play_way', models.TextField(blank=True, null=True, verbose_name='特色玩法')),
                ('traffic', models.TextField(blank=True, null=True, verbose_name='交通到达')),
                ('tips', models.TextField(blank=True, null=True, verbose_name='温馨提示')),
                ('sight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sight.sight')),
            ],
            options={
                'db_table': 'sight_info',
            },
        ),
        migrations.CreateModel(
            name='SightCommet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('love_count', models.IntegerField(default=0, verbose_name='点赞的次数')),
                ('score', models.FloatField(default=5, verbose_name='评分')),
                ('ip_address', models.CharField(blank=True, max_length=128, null=True, verbose_name='ip')),
                ('is_public', models.SmallIntegerField(default=1, verbose_name='是否公开')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='sight.sightcommet', verbose_name='回复id')),
                ('sight', models.ForeignKey(on_delete=models.SET(None), related_name='comments', to='sight.sight', verbose_name='景点')),
                ('user', models.ForeignKey(on_delete=models.SET(None), related_name='comments', to='accounts.user', verbose_name='评论人')),
            ],
            options={
                'db_table': 'sight_comment',
                'ordering': ['-love_count', '-created_at'],
            },
        ),
    ]
